baseURL = 'https://gomonk.dev/'
locale = 'en-us'
title = 'Go monk'
theme = 'paper'

[params]
  # header social icons
  github = 'go-monk'                # github.com/YOUR_GITHUB_ID
  linkedin = 'go-monk'              # linkedin.com/in/YOUR_LINKEDIN_ID
  bluesky = 'go-monk.bsky.social'   # https://bsky.app/profile/YOUR_BLUESKY_ID

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.giscus]
  repo = 'go-monk/gomonk.dev'                 # see https://giscus.app for more details
  repoId = 'R_kgDOTThTCg'
  category = 'Announcements'
  categoryId = 'DIC_kwDOTThTCs4DA6Tt'
  mapping = 'pathname'
  theme = 'preferred_color_scheme'
  lang = 'en'